import { svgs } from "../../../../svgs";
import user1 from '../../../../../assets/user1.svg';
import user2 from '../../../../../assets/user2.svg';
import user3 from '../../../../../assets/user3.svg';

let id = 0;
export const direct3Table = [
    {
        id: id++,
        class: 'header',
        cell1: {icon: false, text: 'Referred'  },
        cell2: {icon: false, text: 'Amount'  },
        cell3: {icon: false, text: 'Package'  },
        cell4: { icon: false, text: 'Percentage' },
        ac: `panel${id}-content`,
        key: `panel${id}`,
        open: false,
    },
    {
        id: id++,
        class: 'row row1',
        cell1: {icon: user1, text: 'Igbo'  },
        cell2: {icon: false, text: '$12.38'  },
        cell3: {icon: false, text: 'Markings 1'  },
        cell4: {icon: false, text: '25%'  },
        ac: `panel${id}-content`,
        key: `panel${id}`,
        open: false,
    },
    {
        id: id++,
        class: 'row row2',
        cell1: {icon: user2, text: 'Igbo'  },
        cell2: {icon: false, text: '$12.38'  },
        cell3: {icon: false, text: 'Markings 1'  },
        cell4: { icon: false, text: '25%' },
         ac: `panel${id}-content`,
        key: `panel${id}`,
        open: false,
    },
    {
        id: id++,
        class: 'row row3',
        cell1: {icon: user3, text: 'Igbo'  },
        cell2: {icon: false, text: '$12.38'  },
        cell3: {icon: false, text: 'Markings 1'  },
        cell4: {icon: false, text: '25%'  },
        ac: `panel${id}-content`,
        key: `panel${id}`,
        open: false,
    },
    {
        id: id++,
        class: 'row row4',
        cell1: {icon: user1, text: 'Igbo'  },
        cell2: {icon: false, text: '$12.38'  },
        cell3: {icon: false, text: 'Markings 1'  },
        cell4: {icon: false, text: '25%'  },
        ac: `panel${id}-content`,
        key: `panel${id}`,
        open: false,
    },
    {
        id: id++,
        class: 'row row5',
        cell1: {icon: user2, text: 'Igbo'  },
        cell2: {icon: false, text: '$12.38'  },
        cell3: {icon: false, text: 'Markings 1'  },
        cell4: {icon: false, text: '25%'  },
        ac: `panel${id}-content`,
        key: `panel${id}`,
        open: false,
    },
    {
        id: id++,
        class: 'row row6',
        cell1: {icon: user3, text: 'Igbo'  },
        cell2: {icon: false, text: '$12.38'  },
        cell3: {icon: false, text: 'Markings 1'  },
        cell4: {icon: false, text: '25%'  },
        ac: `panel${id}-content`,
        key: `panel${id}`,
        open: false,
    },
    {
        id: id++,
        class: 'row row7',
        cell1: {icon: user2, text: 'Igbo'  },
        cell2: {icon: false, text: '$12.38'  },
        cell3: {icon: false, text: 'Markings 1'  },
        cell4: {icon: false, text: '25%'  },
        ac: `panel${id}-content`,
        key: `panel${id}`,
        open: false,
    },
    {
        id: id++,
        class: 'row row8',
        cell1: {icon: user3, text: 'Igbo'  },
        cell2: {icon: false, text: '$12.38'  },
        cell3: {icon: false, text: 'Markings 1'  },
        cell4: {icon: false, text: '25%'  },
        ac: `panel${id}-content`,
        key: `panel${id}`,
        open: false,
    },
]