import { sideSvgs } from "../dashboard/sidebar/sidebarSvgs";
import user1 from '../../assets/toptraderIcon.svg';
import user2 from '../../assets/user2.svg';
import user3 from '../../assets/user3.svg';
import { svgs } from "../svgs";
import Traders from "./traders/Traders";
import Manager from "./manager/Manager";
import Apply from "./apply/Apply";

let id = 0;
export const traderTab = [
    {
        id: id++,
        text: 'Traders',
        icon: sideSvgs.traderlist,
        class: 'active',
        component: <Traders />,
    },
    {
        id: id++,
        text: 'Manager',
        icon: svgs.manager,
        class: '',
         component: <Manager />,
    },
    {
        id: id++,
        text: 'Apply',
        icon: svgs.apply,
        class: '',
         component: <Apply />,
    },
]
let id1 = 0;
export const searchFilter = [
    {
        id: id1++,
        text: '1D',
        active: '',
    },
    {
        id: id1++,
        text: '1W',
        active: '',
    },
    {
        id: id1++,
        text: '1M',
        active: 'active',
    },
    {
        id: id1++,
        text: '1Y',
        active: '',
    },
]


let id2 = 0;

export const all = [
    {
        id: id2++,
        userIcon: user1,
        name: 'Emcode',
        star: svgs.star1,
        star_col: '#95CEA5',
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id2++,
        userIcon: user2,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id2++,
        userIcon: user3,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id2++,
        userIcon: user1,
        name: 'Emcode',
        star: svgs.star1,
        star_col: '#95CEA5',
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id2++,
        userIcon: user2,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id2++,
        userIcon: user3,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id2++,
        userIcon: user1,
        star_col: '#95CEA5',
        name: 'Emcode',
        star: svgs.star1,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id2++,
        userIcon: user2,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id2++,
        userIcon: user3,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
]
let id3 = 0;

export const popular = [
    {
        id: id3++,
        userIcon: user1,
        name: 'Emcode',
        star: svgs.star1,
        star_col: '#95CEA5',
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id3++,
        userIcon: user2,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id3++,
        userIcon: user3,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id3++,
        userIcon: user1,
        name: 'Emcode',
        star: svgs.star1,
        star_col: '#95CEA5',
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id3++,
        userIcon: user2,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id3++,
        userIcon: user3,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id3++,
        userIcon: user1,
        star_col: '#95CEA5',
        name: 'Emcode',
        star: svgs.star1,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id3++,
        userIcon: user2,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
    {
        id: id3++,
        userIcon: user3,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total
    },
]