import { sideSvgs } from "../dashboard/sidebar/sidebarSvgs";
import user1 from '../../assets/toptraderIcon.svg';
import user2 from '../../assets/user2.svg';
import user3 from '../../assets/user3.svg';
import { svgs } from "../svgs";
import Traders from "./traders/Traders";
import Manager from "./manager/Manager";
import Apply from "./apply/Apply";
import Copier from "./manager/copier/Copier";
import Provider from "./manager/provider/Provider";
import Settings from "./manager/settings/Settings";
import Chats from "./manager/chats/Chats";

export const traderTab = [
    {
        id: 1,
        text: 'Traders',
        icon: sideSvgs.traderlist,
        class: 'active',
        component: <Traders />,
    },
    {
        id: 2,
        text: 'Manager',
        icon: svgs.manager,
        class: '',
         component: <Manager />,
    },
    {
        id: 3,
        text: 'Apply',
        icon: svgs.apply,
        class: '',
         component: <Apply />,
    },
]

export const managerTab2 = [
    {
        id:1,
        text: 'Strategy Copier',
        icon: svgs.star3,
        class: '',
        component: <Copier />,
    },
    {
        id:2,
        text: 'Strategy Provider',
        icon: svgs.star3,
        class: 'active',
         component: <Provider />,
    },
   
]
export const managerTab1 = [
    {
        id: 1,
        text: 'Settings',
        icon: svgs.settings,
        class: 'active',
        component: <Settings />,
    },
    {
        id: 2,
        text: 'Chats',
        icon: svgs.chats,
        class: '',
         component: <Chats />,
    },
   
]
export const searchFilter = [
    {
        id: 1,
        text: '1D',
        active: '',
    },
    {
        id: 2,
        text: '1W',
        active: '',
    },
    {
        id: 3,
        text: '1M',
        active: 'active',
    },
    {
        id: 4,
        text: '1Y',
        active: '',
    },
]



export const all = [
    {
        id: 1,
        userIcon: user1,
        name: 'Emcode',
        star: svgs.star1,
        star_col: '#95CEA5',
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
        Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
    {
        id: 2,
        userIcon: user2,
        name: 'Amadi',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
    {
        id: 3,
        userIcon: user3,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
    {
        id: 4,
        userIcon: user1,
        name: 'Emcode',
        star: svgs.star1,
        star_col: '#95CEA5',
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
    {
        id: 5,
        userIcon: user2,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
    {
        id: 6,
        userIcon: user3,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
    {
        id: 7,
        userIcon: user1,
        star_col: '#95CEA5',
        name: 'Emcode',
        star: svgs.star1,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
    {
        id: 8,
        userIcon: user2,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
    {
        id: 8,
        userIcon: user3,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
]

export const popular = [
    {
        id: 1,
        userIcon: user1,
        name: 'Emcode',
        star: svgs.star1,
        star_col: '#95CEA5',
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
        star_dyn: svgs.star_dyn
    },
    {
        id: 2,
        userIcon: user2,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
    {
        id: 3,
        userIcon: user3,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
    {
        id: 4,
        userIcon: user1,
        name: 'Emcode',
        star: svgs.star1,
        star_col: '#95CEA5',
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
    {
        id: 5,
        userIcon: user2,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
    {
        id: 6,
        userIcon: user3,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
    {
        id: 7,
        userIcon: user1,
        star_col: '#95CEA5',
        name: 'Emcode',
        star: svgs.star1,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
    {
        id: 8,
        userIcon: user2,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
    {
        id: 9,
        userIcon: user3,
        name: 'Emcode',
        star: svgs.star,
        avg_text: 'Average Returns',
        avg_rate: '0.00%',
        avg_icon: svgs.networkBar,
        copier_text: 'Copier',
        copier_rate: '3',
        copier_icon: svgs.copier,
        comm_text: 'Commission',
        comm_rate: '4%',
        comm_icon: svgs.dollar,
        total_text: 'Total Profit',
        total_rate: '1.95%',
        total_icon: svgs.total,
         Wallet_Overview: '$0.00',
        Wallet_overview_text: 'Wallet Overview',
        watllet_Overview_icon: svgs.wallect_overview,
        Trader_Balance: '0.00%',
        Trader_Balance_text: 'Trader Balance',
        Closed_Trades: '5',
        Closed_Trades_icon: svgs.Closed_Trades,
        Closed_Trades_text: 'Closed Trades',
        Running_Trades: '3',
        Running_Trades_text: 'Running Trades',
        Running_Trades_icon: svgs.Running_Trades,
         star_dyn: svgs.star_dyn
    },
]