import { svgs } from "../../svgs";

let j = 0;
export const newManualTableHeader = [
     {
        id: 1,
        class: 'header',
        cell1: {icon: false, text: 'Asset'  },
        cell2: {icon: false, text: 'Price'  },
        cell3: {icon: false, text: 'Profit'  },
        cell4: {icon: false, text: 'Timeframe'  },
    },
]
export const newManualTable = [
   
    {
        id: j++,
        class: 'row row1',
        cell1: {icon: svgs.btc, text: 'BTC/USDT'  },
        cell2: {icon: false, text: '$34700.38'  },
        cell3: {icon: false, text: '+0.481%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row2',
        cell1: {icon: svgs.btc, text: 'BTC/USDT'  },
        cell2: {icon: false, text: '$34700.38'  },
        cell3: {icon: false, text: '+0.481%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row3',
        cell1: {icon: svgs.btc, text: 'BTC/USDT'  },
        cell2: {icon: false, text: '$34700.38'  },
        cell3: {icon: false, text: '+0.481%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row4',
        cell1: {icon: svgs.btc, text: 'BTC/USDT'  },
        cell2: {icon: false, text: '$34700.38'  },
        cell3: {icon: false, text: '+0.481%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row5',
        cell1: {icon: svgs.btc, text: 'BTC/USDT'  },
        cell2: {icon: false, text: '$34700.38'  },
        cell3: {icon: false, text: '+0.481%'  },
        cell4: {icon: false, text: '24H'  },
    },
    
    {
        id: j++,
        class: 'row row6',
        cell1: {icon: svgs.eth, text: 'ETH/USDT'  },
        cell2: {icon: false, text: '$1835.55'  },
        cell3: {icon: false, text: '+1.779%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row7',
        cell1: {icon: svgs.eth, text: 'ETH/USDT'  },
        cell2: {icon: false, text: '$1835.55'  },
        cell3: {icon: false, text: '+1.779%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row8',
        cell1: {icon: svgs.eth, text: 'ETH/USDT'  },
        cell2: {icon: false, text: '$1835.55'  },
        cell3: {icon: false, text: '+1.779%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row9',
        cell1: {icon: svgs.eth, text: 'ETH/USDT'  },
        cell2: {icon: false, text: '$1835.55'  },
        cell3: {icon: false, text: '+1.779%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row10',
        cell1: {icon: svgs.bnd, text: 'BNB/USDT'  },
        cell2: {icon: false, text: '$235.7'  },
        cell3: {icon: false, text: '+3.061%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row10',
        cell1: {icon: svgs.bnd, text: 'BNB/USDT'  },
        cell2: {icon: false, text: '$235.7'  },
        cell3: {icon: false, text: '+3.061%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row10',
        cell1: {icon: svgs.bnd, text: 'BNB/USDT'  },
        cell2: {icon: false, text: '$235.7'  },
        cell3: {icon: false, text: '+3.061%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row10',
        cell1: {icon: svgs.bnd, text: 'BNB/USDT'  },
        cell2: {icon: false, text: '$235.7'  },
        cell3: {icon: false, text: '+3.061%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row10',
        cell1: {icon: svgs.bnd, text: 'BNB/USDT'  },
        cell2: {icon: false, text: '$235.7'  },
        cell3: {icon: false, text: '+3.061%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row10',
        cell1: {icon: svgs.bnd, text: 'BNB/USDT'  },
        cell2: {icon: false, text: '$235.7'  },
        cell3: {icon: false, text: '+3.061%'  },
        cell4: {icon: false, text: '24H'  },
    },

    {
        id: j++,
        class: 'row row1',
        cell1: {icon: svgs.btc, text: 'BTC/USDT'  },
        cell2: {icon: false, text: '$34700.38'  },
        cell3: {icon: false, text: '+0.481%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row2',
        cell1: {icon: svgs.btc, text: 'BTC/USDT'  },
        cell2: {icon: false, text: '$34700.38'  },
        cell3: {icon: false, text: '+0.481%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row3',
        cell1: {icon: svgs.btc, text: 'BTC/USDT'  },
        cell2: {icon: false, text: '$34700.38'  },
        cell3: {icon: false, text: '+0.481%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row4',
        cell1: {icon: svgs.btc, text: 'BTC/USDT'  },
        cell2: {icon: false, text: '$34700.38'  },
        cell3: {icon: false, text: '+0.481%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row5',
        cell1: {icon: svgs.btc, text: 'BTC/USDT'  },
        cell2: {icon: false, text: '$34700.38'  },
        cell3: {icon: false, text: '+0.481%'  },
        cell4: {icon: false, text: '24H'  },
    },
    
    {
        id: j++,
        class: 'row row6',
        cell1: {icon: svgs.eth, text: 'ETH/USDT'  },
        cell2: {icon: false, text: '$1835.55'  },
        cell3: {icon: false, text: '+1.779%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row7',
        cell1: {icon: svgs.eth, text: 'ETH/USDT'  },
        cell2: {icon: false, text: '$1835.55'  },
        cell3: {icon: false, text: '+1.779%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row8',
        cell1: {icon: svgs.eth, text: 'ETH/USDT'  },
        cell2: {icon: false, text: '$1835.55'  },
        cell3: {icon: false, text: '+1.779%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row9',
        cell1: {icon: svgs.eth, text: 'ETH/USDT'  },
        cell2: {icon: false, text: '$1835.55'  },
        cell3: {icon: false, text: '+1.779%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row10',
        cell1: {icon: svgs.bnd, text: 'BNB/USDT'  },
        cell2: {icon: false, text: '$235.7'  },
        cell3: {icon: false, text: '+3.061%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row10',
        cell1: {icon: svgs.bnd, text: 'BNB/USDT'  },
        cell2: {icon: false, text: '$235.7'  },
        cell3: {icon: false, text: '+3.061%'  },
        cell4: {icon: false, text: '24H'  },
    },
    {
        id: j++,
        class: 'row row10',
        cell1: {icon: svgs.bnd, text: 'BNB/USDT'  },
        cell2: {icon: false, text: '$235.7'  },
        cell3: {icon: false, text: '+3.061%'  },
        cell4: {icon: false, text: '24H'  },
    },
    
]